Building configuration...

Current configuration:
!
frr version 10.0
frr defaults traditional
hostname 77c86c284db3
no ipv6 forwarding
service integrated-vtysh-config
!
interface eth0
 description LAN_PC1_192.168.110.0/24
 ip address 192.168.110.254/24
exit
!
interface eth1
 description LINK_R1_R2_10.1.12.0/24
 ip address 10.1.12.2/24
exit
!
router rip
 network 192.168.110.0/24
 network 10.1.12.0/24
 version 2
exit
!
end
