Building configuration...

Current configuration:
!
frr version 10.0
frr defaults traditional
hostname 55968d8268db
no ipv6 forwarding
service integrated-vtysh-config
!
ip route 192.168.10.0/24 10.0.12.2
ip route 192.168.30.0/24 10.0.23.3
!
interface eth0
 description LINK_R1_R2_10.0.12.0/24
 ip address 10.0.12.3/24
exit
!
interface eth1
 description LINK_R2_R3_10.0.23.0/24
 ip address 10.0.23.2/24
exit
!
end
